### PR TITLE
make the full dump of mdat easier for human to read.

### PR DESCRIPTION
**Pull request by kuroishi**
@sunfish-shogi

When the mdat is fully dumped, the output is out of alignment and in one line.
In case the mdat data is not small, one line output sometimes bothers some pagers such as the less command. In addition to that, the current behavior of displaying mdat HEX isn't quite readable I think.

This PR displays like below.
```
% ./mp4tool  dump -full mdat /tmp/1.mp4
[moof] Size=865
  [mfhd] Size=16 Version=0 Flags=0x000000 SequenceNumber=1
  [traf] Size=841
    [tfhd] Size=16 Version=0 Flags=0x000000 TrackID=1
    [tfdt] Size=20 Version=1 Flags=0x000000 BaseMediaDecodeTimeV1=3750
    [trun] Size=740 ... (use "-full trun" to show all)
    [sdtp] Size=57 ... (use "-full sdtp" to show all)
[mdat] Size=1052 Data=[
    00 00 00 02 09 f0 00 00 00 3f 65 88 84 00 2f ff
    f9 18 ee fe a3 a8 8b ac b7 fb ea d5 a4 b2 73 4c
    43 6f 5c 43 32 93 8c 61 ec 80 00 00 03 00 00 67
    9c c0 f7 44 cd 1d cb 7a 08 00 01 92 00 0f 32 7d
    09 79 c5 6f e1 bd fc 38 a1 00 00 00 02 09 f0 00
    00 00 0c 41 9a 24 18 85 ff fd e1 00 00 1b d0 00
    00 00 02 09 f0 00 00 00 09 41 9e 42 02 3f ff 00
    :
    :
```

I would appreciate it if you could consider it. Thanks.

### CODE REVIEW

**Comment by sunfish-shogi** [comment]
@kuroishi 
Thank you for your pull request!

I designed to write one box as one line to be useful for UNIX command pipeline (ex. grep).
However, mdat box is often very large and I agree your suggestion.

I have an additional suggestion about this pull request.
`h.ReadPayload`, `mp4.Stringify` and `strings.Split` use very large memory for mdat box.
And `strings.Index` is simple linear search.
Adding code block dedicated to mdat box, I think that `mp4.Strigify` has no advantages.
So, I think it is better to use `io.Seeker` and `io.Reader` directly instead of those functions.

If you think this performace issue is not scope in this PR, I will merge this PR and create new issue.

**Comment by kuroishi** [comment]
Hi, thanks for your response.

> Adding code block dedicated to mdat box, I think that mp4.Strigify has no advantages.

You mean that mp4.Stringfy shouldn't be used and it's better to use some new logic using io.Seeker and io.Reader when fully dumping the mdat box, right?

**Comment by sunfish-shogi** [comment]
> You mean that mp4.Stringfy shouldn't be used and it's better to use some new logic using io.Seeker and io.Reader when fully dumping the mdat box, right?

Yes.

`ReadPayload` loads all of payload to `mp4.Mdat` struct and `mp4.Stringify` creates very large string which several times of mdat box size.
This is existing problem, but I thinked that dumping mdat box is rare use case and it is not important.

However, if not, I think `ReadPayload` and `mp4.Strigify` are not good to use.
Because non fragmented MP4 has often very large (sometimes more than 1 GB) payload.
And this PR requires more memory and CPU resources.

As mentioned above, basically this is existing problem.
So, I don’t think neccesary to resolve in this PR.
But I want you to allow that I change this implementation on new PR.

And I have one more suggestion.
I think creating following new command is usefull for more use cases.

```
Usage:
    mp4dump extract [OPTIONS] BOX_TYPE

Example:
    mp4dump extract -no-header mdat | hexdump -C
```

This command is not exist yet. But I think I can create its first version in a short term.

**Comment by kuroishi** [comment]
ok. I'll try to implement it as you advise and create new PR.

**Comment by sunfish-shogi** [comment]
@kuroishi 
Thank you!

Please let me add more information.

I said:

> I think it is better to use io.Seeker and io.Reader directly instead of those functions.

But go-mp4 already has a wrapper function [SeekToPayload](https://pkg.go.dev/github.com/abema/go-mp4#BoxInfo.SeekToPayload) instead of call Seek fuction directly .
This function sets the offset to next byte of box header.

Actually, ReadPayload function uses it.
https://github.com/abema/go-mp4/blob/master/read.go#L94

**Comment by sunfish-shogi** [comment]
@kuroishi 

I just created new command `mp4tool-extract` which I presented as alternative solution.
https://github.com/abema/go-mp4/pull/105

This command can extract box which has specified type and output to stdout.
So, you can see hex and characters with `| hexdump -C`.

Does this command matches to your motivation?

**Comment by kuroishi** [comment]
looks good. 

  # sorry for delayed response. I was sick and I have a deadline for other work.

**Comment by sunfish-shogi** [comment]
merged https://github.com/abema/go-mp4/pull/105

**Pull request closed without merging**
